In [53]:
import pandas as pd
import json

In [54]:
with open("country2continent.json") as f:
    countries = list(json.load(f).keys())

print(countries)

['Bolivia', 'Ecuador', 'Nigeria', 'Indonesia', 'Chile', 'Germany', 'Andorra', 'Japan', 'Malaysia', 'Unknown', 'Philippines', 'Puerto Rico', 'Kenya', 'Guatemala', 'Romania', 'Cyprus', 'Kazakhstan', 'Czech Republic', 'Brazil', 'Ethiopia', 'Thailand', 'United Kingdom', 'Vietnam', 'Tunisia', 'United States of America', 'Netherlands', 'Iraq', 'Singapore', 'Colombia', 'Bangladesh', 'Russia', 'Venezuela', 'Kyrgyzstan', 'Slovakia', 'Iran', 'Armenia', 'Myanmar', 'Nicaragua', 'Ukraine', 'Mongolia', 'Mexico', 'China', 'Taiwan', 'Egypt', 'Australia', 'Libya', 'Greece', 'Uruguay', 'Zimbabwe', 'Morocco', 'Canada', 'South Korea', 'Peru', 'Tajikistan', 'New Zealand', 'Turkey', 'Lebanon', 'Hong Kong', 'Pakistan', 'Jordan', 'Argentina']

In [55]:
df = pd.read_excel(r"CLASS.xlsx", engine='openpyxl')
df

,Economy,Code,Region,Income group,Lending category,Unnamed: 5
0,Aruba,ABW,Latin America & Caribbean,High income,NaN,NaN
1,Afghanistan,AFG,South Asia,Low income,IDA,NaN
2,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD,NaN
3,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD,NaN
4,Andorra,AND,Europe & Central Asia,High income,NaN,NaN
...,...,...,...,...,...,...
264,Sub-Saharan Africa (IDA & IBRD),TSS,NaN,NaN,NaN,NaN
265,Upper middle income,UMC,NaN,NaN,NaN,NaN
266,World,WLD,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
all_country2income = dict(zip(df['Economy'], df['Income group']))
all_country2income

{'Aruba': 'High income',
 'Afghanistan': 'Low income',
 'Angola': 'Lower middle income',
 'Albania': 'Upper middle income',
 'Andorra': 'High income',
 'United Arab Emirates': 'High income',
 'Argentina': 'Upper middle income',
 'Armenia': 'Upper middle income',
 'American Samoa': 'High income',
 'Antigua and Barbuda': 'High income',
 'Australia': 'High income',
 'Austria': 'High income',
 'Azerbaijan': 'Upper middle income',
 'Burundi': 'Low income',
 'Belgium': 'High income',
 'Benin': 'Lower middle income',
 'Burkina Faso': 'Low income',
 'Bangladesh': 'Lower middle income',
 'Bulgaria': 'Upper middle income',
 'Bahrain': 'High income',
 'Bahamas, The': 'High income',
 'Bosnia and Herzegovina': 'Upper middle income',
 'Belarus': 'Upper middle income',
 'Belize': 'Upper middle income',
 'Bermuda': 'High income',
 'Bolivia': 'Lower middle income',
 'Brazil': 'Upper middle income',
 'Barbados': 'High income',
 'Brunei Darussalam': 'High income',
 'Bhutan': 'Lower middle income',
 'Botswana': 'Upper middle income',
 'Central African Republic': 'Low income',
 'Canada': 'High income',
 'Switzerland': 'High income',
 'Channel Islands': 'High income',
 'Chile': 'High income',
 'China': 'Upper middle income',
 'Côte d’Ivoire': 'Lower middle income',
 'Cameroon': 'Lower middle income',
 'Congo, Dem. Rep.': 'Low income',
 'Congo, Rep.': 'Lower middle income',
 'Colombia': 'Upper middle income',
 'Comoros': 'Lower middle income',
 'Cabo Verde': 'Lower middle income',
 'Costa Rica': 'Upper middle income',
 'Cuba': 'Upper middle income',
 'Curaçao': 'High income',
 'Cayman Islands': 'High income',
 'Cyprus': 'High income',
 'Czechia': 'High income',
 'Germany': 'High income',
 'Djibouti': 'Lower middle income',
 'Dominica': 'Upper middle income',
 'Denmark': 'High income',
 'Dominican Republic': 'Upper middle income',
 'Algeria': 'Lower middle income',
 'Ecuador': 'Upper middle income',
 'Egypt, Arab Rep.': 'Lower middle income',
 'Eritrea': 'Low income',
 'Spain': 'High income',
 'Estonia': 'High income',
 'Ethiopia': 'Low income',
 'Finland': 'High income',
 'Fiji': 'Upper middle income',
 'France': 'High income',
 'Faroe Islands': 'High income',
 'Micronesia, Fed. Sts.': 'Lower middle income',
 'Gabon': 'Upper middle income',
 'United Kingdom': 'High income',
 'Georgia': 'Upper middle income',
 'Ghana': 'Lower middle income',
 'Gibraltar': 'High income',
 'Guinea': 'Lower middle income',
 'Gambia, The': 'Low income',
 'Guinea-Bissau': 'Low income',
 'Equatorial Guinea': 'Upper middle income',
 'Greece': 'High income',
 'Grenada': 'Upper middle income',
 'Greenland': 'High income',
 'Guatemala': 'Upper middle income',
 'Guam': 'High income',
 'Guyana': 'High income',
 'Hong Kong SAR, China': 'High income',
 'Honduras': 'Lower middle income',
 'Croatia': 'High income',
 'Haiti': 'Lower middle income',
 'Hungary': 'High income',
 'Indonesia': 'Upper middle income',
 'Isle of Man': 'High income',
 'India': 'Lower middle income',
 'Ireland': 'High income',
 'Iran, Islamic Rep.': 'Lower middle income',
 'Iraq': 'Upper middle income',
 'Iceland': 'High income',
 'Israel': 'High income',
 'Italy': 'High income',
 'Jamaica': 'Upper middle income',
 'Jordan': 'Lower middle income',
 'Japan': 'High income',
 'Kazakhstan': 'Upper middle income',
 'Kenya': 'Lower middle income',
 'Kyrgyz Republic': 'Lower middle income',
 'Cambodia': 'Lower middle income',
 'Kiribati': 'Lower middle income',
 'St. Kitts and Nevis': 'High income',
 'Korea, Rep.': 'High income',
 'Kuwait': 'High income',
 'Lao PDR': 'Lower middle income',
 'Lebanon': 'Lower middle income',
 'Liberia': 'Low income',
 'Libya': 'Upper middle income',
 'St. Lucia': 'Upper middle income',
 'Liechtenstein': 'High income',
 'Sri Lanka': 'Lower middle income',
 'Lesotho': 'Lower middle income',
 'Lithuania': 'High income',
 'Luxembourg': 'High income',
 'Latvia': 'High income',
 'Macao SAR, China': 'High income',
 'St. Martin (French part)': 'High income',
 'Morocco': 'Lower middle income',
 'Monaco': 'High income',
 'Moldova': 'Upper middle income',
 'Madagascar': 'Low income',
 'Maldives': 'Upper middle income',
 'Mexico': 'Upper middle income',
 'Marshall Islands': 'Upper middle income',
 'North Macedonia': 'Upper middle income',
 'Mali': 'Low income',
 'Malta': 'High income',
 'Myanmar': 'Lower middle income',
 'Montenegro': 'Upper middle income',
 'Mongolia': 'Lower middle income',
 'Northern Mariana Islands': 'High income',
 'Mozambique': 'Low income',
 'Mauritania': 'Lower middle income',
 'Mauritius': 'Upper middle income',
 'Malawi': 'Low income',
 'Malaysia': 'Upper middle income',
 'Namibia': 'Upper middle income',
 'New Caledonia': 'High income',
 'Niger': 'Low income',
 'Nigeria': 'Lower middle income',
 'Nicaragua': 'Lower middle income',
 'Netherlands': 'High income',
 'Norway': 'High income',
 'Nepal': 'Lower middle income',
 'Nauru': 'High income',
 'New Zealand': 'High income',
 'Oman': 'High income',
 'Pakistan': 'Lower middle income',
 'Panama': 'High income',
 'Peru': 'Upper middle income',
 'Philippines': 'Lower middle income',
 'Palau': 'Upper middle income',
 'Papua New Guinea': 'Lower middle income',
 'Poland': 'High income',
 'Puerto Rico': 'High income',
 "Korea, Dem. People's Rep.": 'Low income',
 'Portugal': 'High income',
 'Paraguay': 'Upper middle income',
 'West Bank and Gaza': 'Upper middle income',
 'French Polynesia': 'High income',
 'Qatar': 'High income',
 'Romania': 'High income',
 'Russian Federation': 'Upper middle income',
 'Rwanda': 'Low income',
 'Saudi Arabia': 'High income',
 'Sudan': 'Low income',
 'Senegal': 'Lower middle income',
 'Singapore': 'High income',
 'Solomon Islands': 'Lower middle income',
 'Sierra Leone': 'Low income',
 'El Salvador': 'Upper middle income',
 'San Marino': 'High income',
 'Somalia': 'Low income',
 'Serbia': 'Upper middle income',
 'South Sudan': 'Low income',
 'São Tomé and Príncipe': 'Lower middle income',
 'Suriname': 'Upper middle income',
 'Slovak Republic': 'High income',
 'Slovenia': 'High income',
 'Sweden': 'High income',
 'Eswatini': 'Lower middle income',
 'Sint Maarten (Dutch part)': 'High income',
 'Seychelles': 'High income',
 'Syrian Arab Republic': 'Low income',
 'Turks and Caicos Islands': 'High income',
 'Chad': 'Low income',
 'Togo': 'Low income',
 'Thailand': 'Upper middle income',
 'Tajikistan': 'Lower middle income',
 'Turkmenistan': 'Upper middle income',
 'Timor-Leste': 'Lower middle income',
 'Tonga': 'Upper middle income',
 'Trinidad and Tobago': 'High income',
 'Tunisia': 'Lower middle income',
 'Türkiye': 'Upper middle income',
 'Tuvalu': 'Upper middle income',
 'Taiwan, China': 'High income',
 'Tanzania': 'Lower middle income',
 'Uganda': 'Low income',
 'Ukraine': 'Lower middle income',
 'Uruguay': 'High income',
 'United States': 'High income',
 'Uzbekistan': 'Lower middle income',
 'St. Vincent and the Grenadines': 'Upper middle income',
 'Venezuela, RB': nan,
 'British Virgin Islands': 'High income',
 'Virgin Islands (U.S.)': 'High income',
 'Vietnam': 'Lower middle income',
 'Vanuatu': 'Lower middle income',
 'Samoa': 'Lower middle income',
 'Kosovo': 'Upper middle income',
 'Yemen, Rep.': 'Low income',
 'South Africa': 'Upper middle income',
 'Zambia': 'Lower middle income',
 'Zimbabwe': 'Lower middle income',
 nan: nan,
 'Africa Eastern and Southern': nan,
 'Africa Western and Central': nan,
 'Arab World': nan,
 'Caribbean small states': nan,
 'Central Europe and the Baltics': nan,
 'Early-demographic dividend': nan,
 'East Asia & Pacific': nan,
 'East Asia & Pacific (excluding high income)': nan,
 'East Asia & Pacific (IDA & IBRD)': nan,
 'Euro area': nan,
 'Europe & Central Asia': nan,
 'Europe & Central Asia (excluding high income)': nan,
 'Europe & Central Asia (IDA & IBRD)': nan,
 'European Union': nan,
 'Fragile and conflict affected situations': nan,
 'Heavily indebted poor countries (HIPC)': nan,
 'High income': nan,
 'IBRD only': nan,
 'IDA & IBRD total': nan,
 'IDA blend': nan,
 'IDA only': nan,
 'IDA total': nan,
 'Late-demographic dividend': nan,
 'Latin America & Caribbean': nan,
 'Latin America & Caribbean (excluding high income)': nan,
 'Latin America & Caribbean (IDA & IBRD)': nan,
 'Least developed countries: UN classification': nan,
 'Low & middle income': nan,
 'Low income': nan,
 'Lower middle income': nan,
 'Middle East & North Africa': nan,
 'Middle East & North Africa (excluding high income)': nan,
 'Middle East & North Africa (IDA & IBRD)': nan,
 'Middle income': nan,
 'North America': nan,
 'OECD members': nan,
 'Other small states': nan,
 'Pacific island small states': nan,
 'Post-demographic dividend': nan,
 'Pre-demographic dividend': nan,
 'Small states': nan,
 'South Asia': nan,
 'South Asia (IDA & IBRD)': nan,
 'Sub-Saharan Africa': nan,
 'Sub-Saharan Africa (excluding high income)': nan,
 'Sub-Saharan Africa (IDA & IBRD)': nan,
 'Upper middle income': nan,
 'World': nan}

In [ ]:
label_dict = {
    "High income": "high",
    "Upper middle income": "upper-middle",
    "Lower middle income": "lower-middle",
    "Low income": "low"
}

In [57]:
country2income = dict()
missing = list()
for country in countries:
    if country in all_country2income:
        country2income[country] = label_dict[all_country2income[country]]
    else:
        missing.append(country)

In [58]:
with open("country2income.json", mode="w") as f:
    json.dump(country2income, f, indent=4)

In [59]:
print(missing)

['Unknown', 'Czech Republic', 'United States of America', 'Russia', 'Venezuela', 'Kyrgyzstan', 'Slovakia', 'Iran', 'Taiwan', 'Egypt', 'South Korea', 'Turkey', 'Hong Kong']